name: Check Branches
"on":
  pull_request:
    branches:
      - dvp
      - release/rls**
jobs:
  Checking-Branch-Rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Check Branch Names
        run: |
          if [[ "${{github.base_ref}}" =~ "dvp" && "${{github.head_ref}}" =~ ^(feat|fix)\/]];
             then echo " Branching rules applied and the result is 'OK ✅' "
          else 
             then echo "ERROR⛔: Branch name must start with 'feat/' or 'fix/' --> Exiting..."
             exit 1
          fi
