name: Check Branches
"on":
  pull_request:
    branches:
      - dvp
      - release/rls**
jobs:
  Checking-Branch-Rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Check Branch Names  - dvp
        env: 
            FULL_BRANCH_NAME: ${{ format('{0}/{1}', github.base_ref, github.head_ref) }}
        if: ${{ !contains(env.FULL_BRANCH_NAME, 'dvp/fix/') || !contains(env.FULL_BRANCH_NAME, 'dvp/feat/') }}
        run: |
             echo "ERROR⛔: ${{ env.FULL_BRANCH_NAME }} Branch name ( ${{github.head_ref}} ) must start with 'feat/' or 'fix/' --> Exiting..."
             exit 1
             
      # - name: Check Branch Names - release/rls#.#
      #   if: ${{ startsWith(github.base_ref, 'release/rls') && !startsWith(github.head_ref,'rls') || !startsWith(github.head_ref,'rls') && !(contains(github.head_ref, '/feat') || contains(github.head_ref, '/fix'))  }}
      #   run: |
      #        echo "ERROR⛔: Branch name  ( ${{github.head_ref}} ) must start with 'rls#.#/feat/' or 'rls#.#/fix/' --> Exiting..."
      #        exit 1
