name: Check Branches
"on":
  pull_request:
    branches:
      - dvp
      - release/rls**
jobs:
  Checking-Branch-Rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Check Branch Names - DVP
        if: ${{github.base_ref == 'dvp' && !startsWith(github.head_ref, 'fix/') ||  github.base_ref == 'dvp' && !startsWith(github.head_ref, 'feat/') }}
        run: |
             echo "ERROR⛔: Branch name must start with 'feat/' or 'fix/' --> Exiting..."
             exit 1
             
      - name: Check Branch Names - release/rls#.#
        if: ${{ github.base_ref.match('^release/rls\\d+\\.d+$') && !github.head_ref.match('^rls\\d+\\.\\d+\\/(?:feat|fix)') }}
        run: |
             echo "ERROR⛔: Branch name must start with 'rls#.#/feat/' or 'rls#.#/fix/' --> Exiting..."
             exit 1
